permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Him & Her Watches"
  description: Luxuriously affordable watches for him and her to enjoy in various colors, styles and materials.
  font_url: "https://use.typekit.net/kuf4pid.css"
  rationales:
    typefaces.primary: |
      Bodoni 72 was selected for its elegant and easily readable serifs. It compliments the theme of the website.
    typefaces.secondary: |
      Brandgon Grotesque is only to be used for buttons, hero banner text, item description/cost.
    colors.primary: |
        The primary colors represent the elegant and suave tone set for the theme of the site. The colors are also gender neutral. They should be used for the header, text, foreground.
    colors.secondary: |
        The secondary colors are for the background. They should be used to for less important elements on the page.
    colors.accent: |
      The accent color is for cards and buttons on the site to accentuate them.

  colors:
    background: "--color-secondary-light"
    patterns:
      brand.logos: "--color-primary"
  layouts:
    default: |
      The default layout should be use for almost every page, it includes the websit'es primary header and footer.
    products: |
      The products are displayed accordingly once the link is clicked from every other page.
collections:
  products:
      output: true
defaults:
  - scope:
      path: _products
    values:
      layout: products
