title: "Buttons"
  description: |
  Buttons should be used in situations where a dramatic, obvious action is required. Try not to over use buttons because they should be the primary call-to-action for a screen.

patterns:
  basic:
    title: "Basic"
    description: |
    Default to using the basic button. It should always in front of light backgrounds.
    width: "12em"
    background: "--color-accent"
  ghost:
    title: "Ghost"
    description: |
    The ghost button is specifically for banners/cards, where it will be placed in front of busy images.
    background: "--color-primary-dark"
  light:
    title: "light"
    description: |
    The light button is primarily for contrast and are located on cards.
    background: "--color-primary-light"
  big:
    title: "big"
      description: |
      The big button is primarily for important content such as completing an order.
