title: "Navigation"
description: |
  Navigation will pertain to filtering through different pages on the website. A "previous" and "next" button is visible, as well as the number of page you're currently on and the remaining pages. A "skip to" navigation button is also available.
